name: automated-pr-approve
on:
  workflow_dispatch:
  schedule:
    - cron: "*/45 * * * *"

permissions:
  contents: read

jobs:
  review-pr:
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/os'

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - run: |
          ./scripts/auto-approve-pr.sh ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
