name: Wolfictl Check Updates

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - gh-readonly-queue/main/**

permissions:
  contents: read

jobs:
  lint:
    name: Wolfictl Check Updates
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@rc
        with:
          egress-policy: audit

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Get changed files
        id: files
        uses: tj-actions/changed-files@40853de9f8ce2d6cfdc73c1b96f14e22ba44aec4 # v45.0.0
        with:
          separator: " "
          files: "*.yaml"
          files_ignore: ".yam.yaml"

      - name: Check
        id: check
        # this need to point to main to always get the latest action
        uses: wolfi-dev/actions/wolfictl-check-updates@main # main
        if: ${{ steps.files.outputs.all_changed_files != '' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          changed_files: ${{ steps.files.outputs.all_changed_files }}
